<?php

use Drupal\Core\Url;
use Drupal\facets\FacetInterface;
use Symfony\Component\Routing\Exception\RouteNotFoundException;

/**
 * Implements hook_theme().
 */
function commerce_oasis_theme()
{
  return [
    'oasis_settings'           => [
      'variables' => [],
    ],
    'commerce_oasis_frontpage' => [
      'variables' => [
        'featured_products' => [],
      ],
    ],
    'oasis_orders'             => [
      'variables' => [
        'validate' => FALSE,
        'orders'   => [],
      ],
    ],
  ];
}

/**
 * @file
 *
 * hook_page_attachments()
 */
function commerce_oasis_page_attachments(array &$page)
{
  $page['#attached']['library'][] = 'commerce_oasis/commerce.belgrade';
}

/**
 * Implements hook_menu_links_discovered_alter().
 *
 * Workaround for taxonomy_menu not supporting custom paths. See #2865894.
 */
function commerce_oasis_menu_links_discovered_alter(&$links)
{
  $alias_cleaner = \Drupal::service('pathauto.alias_cleaner');
  $facet_storage = \Drupal::entityTypeManager()->getStorage('facets_facet');
  $term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  try {
    $view_url = Url::fromRoute('view.product_catalog.page_1');
    $view_url = $view_url->getInternalPath();
  } catch (RouteNotFoundException $e) {
    // The catalog View may have been disabled or deleted.
    return;
  }

  foreach ($links as &$link) {
    $menu_name = isset($link['menu_name']) ? $link['menu_name'] : '';
    if ($link['provider'] == 'taxonomy_menu' && $menu_name == 'catalog') {
      // Generate the path to the view + facets.
      // Assumes that the facet is named the same as the vocabulary.
      $term = $term_storage->load($link['metadata']['taxonomy_term_id']);
      $facet = $facet_storage->load($term->bundle());
      if (!$facet instanceof FacetInterface) {
        continue;
      }

      // It is possible for the facet to be NULL if it was deleted, in which
      // case we only link to the view (which is better than nothing).
      $link['url'] = 'internal:/' . $view_url;
      if ($facet) {
        $label = $alias_cleaner->cleanString($term->label());
        $link['url'] .= '/' . $facet->getUrlAlias() . '/' . $label . '-' . $term->id();
      }
      $link['route_name'] = '';
      $link['route_parameters'] = [];
      $link['load arguments'] = [];
    }
  }
}

/**
 * Implements hook_preprocess_breadcrumb().
 */
function commerce_oasis_preprocess_breadcrumb(&$variables)
{
  // The Bootstrap theme provides a feature that appends the current page title
  // to the end of the breadcrumbs. On the catalog page this is awkward, as
  // Facets already appends the facet source page title when a facet filter
  // is active.
  //
  // This temporarily disables that setting, as module preprocess hooks will run
  // before the theme's, without actually changing the theme setting.
  if (class_exists('\Drupal\bootstrap\Plugin\Preprocess\Breadcrumb')) {
    $current_route_match = \Drupal::routeMatch();
    if ($current_route_match->getRouteName() == 'view.product_catalog.page_1') {
      $theme = \Drupal\bootstrap\Bootstrap::getTheme();
      $theme->setSetting('breadcrumb_title', FALSE);
    }
  }
}
